### ISSUE TITLE
Refactor: `test` workflow

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#19]
We have a [test](https://github.com/Nautilus-Cyberneering/git-queue/blob/main/.github/workflows/test.yml) workflow which does two things:

- Run unit and e2e tests with `yarn test`
- Run all the action commands (`create-job`, `next-job`, `mark-job-as-done`) in the current branch.

I think we could refactor that `workflow` to include 3 jobs:

- Unit tests: all except `main.test.ts`
- E2e tests: only `main.test.ts`
- Integration tests: workflows steps using the GitHub Action.

The reason why `main.test.ts` is a little bit different is that it requires building the app (`yarn build`) and it uses the app as a console app running `node src/lib/main.js`.

Regarding integration tests, I think we should test the action commands in a different git repo, not in the same branch we are working on as we do for the other tests. We need to create a new initialized git repo and run the action using the testing repo. This way we avoid adding spurious git commits.

**Comment by josecelano** [comment]
I've found a hidden bug after refactoring the `test` workflow. You need to setup the git committer identity before using the action. You can do it for example with:

```console
git config --global user.name 'github-actions[bot]'
git config --global user.email 'github-actions[bot]@users.noreply.github.com'
```

if you want to use the GitHub Bot.

The error was hidden because in my local machine I have it and in the previous workflow we were using this action which set up the global user config (`git_config_global: true`):

```
- name: Import GPG key
  id: import-gpg
  uses: crazy-max/ghaction-import-gpg@v4
  with:
    gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
    passphrase: ${{ secrets.PASSPHRASE }}
    git_config_global: true
    git_user_signingkey: true
    git_commit_gpgsign: false
    fingerprint: 'BD98B3F42545FF93EFF55F7F3F39AA1432CA6AD7'
```

I think the action should fail if it does not find that configuration, at least for the commands that generate a commit.

what do you think @da2ce7 , @yeraydavidrodriguez ? [This](https://github.com/Nautilus-Cyberneering/git-queue/blob/main/src/simple-git-factory.ts) is the factory class from `SimpleGit`.
