### ISSUE TITLE
Tests are not being executed on PR from forks

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#217]
When you create a PR from a forked repo the `test.yml` workflow is not triggered. That's because it only has the "push" event. We were initially working only with branches in the same repo. We need to add the `pull_request` event:

```
on:
  pull_request:
  push:
    branches: [main, issue-*]
  workflow_dispatch:
```
