### ISSUE TITLE
Multi-job queue: allow more than 1 pending job in the queue

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#30]
Depends on: https://github.com/Nautilus-Cyberneering/git-queue/issues/38

Right now the queue only allows one pending job. If there is a not finished job the queue does not allow adding more jobs. We want to allow N jobs in the queue.

In order to implement this feature we need to add an extra input to the action when we use the `finish-job` or other action that might require the job id:

```yml
- name: Mark job as finished
  id: finish-job
  if: ${{ steps.create-job.outputs.job_created == 'true' }}
  uses: ./
  with:
    git_repo_dir: ${{ runner.temp }}/temp_git_dir
    queue_name: 'Library Update [library-aaa]'
    action: 'finish-job'
    job_payload: '{"field": "value", "state": "finished", "job_id": 15}'
    job_id: 15
```

Notice the new input `job_id: 15`
