### ISSUE TITLE
Overwrite the author of the commit

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#31]
In the current implementation, the commit author is the same as the committer but we allow to override it with an action input:

```
git_commit_author:
  description: 'The git commit --author argument: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---authorltauthorgt'
  required: false
  default: ''
```

@da2ce7 proposed to set the action as the author. The changes are:

- Do not allow to overwrite the commit author.
- Always use this author: `Git-Queue GitHub Action <bot@nautilus-cyberneering.de>`

Issue imported from : https://github.com/josecelano/library-consumer/issues/16
