### ISSUE TITLE
Improve error message when no committer configuration is available

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#34]
I've found a hidden "bug" (or not friendly error) after refactoring the `test` workflow. You need to setup the git committer identity before using the action. You can do it for example with:

```console
git config --global user.name 'github-actions[bot]'
git config --global user.email 'github-actions[bot]@users.noreply.github.com'
```

if you want to use the GitHub Bot.

The error was hidden because in my local machine I have it and in the previous workflow we were using this action which set up the global user config (`git_config_global: true`):

```
- name: Import GPG key
  id: import-gpg
  uses: crazy-max/ghaction-import-gpg@v4
  with:
    gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
    passphrase: ${{ secrets.PASSPHRASE }}
    git_config_global: true
    git_user_signingkey: true
    git_commit_gpgsign: false
    fingerprint: 'BD98B3F42545FF93EFF55F7F3F39AA1432CA6AD7'
```

I think the action should fail if it does not find that configuration, at least for the commands that generate a commit.

what do you think @da2ce7 , @yeraydavidrodriguez ? [This](https://github.com/Nautilus-Cyberneering/git-queue/blob/main/src/simple-git-factory.ts) is the factory class from `SimpleGit`.

_Originally posted by @josecelano in https://github.com/Nautilus-Cyberneering/git-queue/issues/19#issuecomment-1032887039_
