### ISSUE TITLE
Why we need to build & package the action on each commit?

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#36]
The `check-dist.yml` workflows check that you have built and packaged the action for the current commit. It's triggered on every push to a PR. It's pretty annoying because you always see an error in your PR checklist:

![image](https://user-images.githubusercontent.com/58816/153376863-839ce808-caef-4aab-825d-02137ae43a3a.png)

I usually only build&package when the PR is ready to review. I was wondering if we can remove that workflow because, [in the long run](https://github.com/Nautilus-Cyberneering/git-queue/issues/6), I was planning to release automatically using a git tag.

But I've just realised you can use any action commit. See https://github.com/actions/toolkit/blob/master/docs/action-versioning.md

```
steps:
    - uses: actions/javascript-action@v1        # recommended. starter workflows use this
    - uses: actions/javascript-action@v1.0.0    # if an action offers specific releases 
    - uses: actions/javascript-action@41775a4da8ffae865553a738ab8ac1cd5a3c0044 # sha
```

So each commit we merge into main should have the `dist/index.js` file with the right version.

If you do not want to see the failed workflow in the pull request you have to always run `yarn build && yarn package` before pushing. I usually use this commit subject "yarn build & yarn update".

@da2ce7 @yeraydavidrodriguez any other idea? I know that @da2ce7 did not like to include the `dist/index.js` file in the PRs.

If we don't have any other idea at least we can add a comment to the workflow as a reminder for why we need it.
