### ISSUE TITLE
Test action with Windows and macOS 

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#49]
The action has been developed using Linux and we are only using Ubuntu in the workflows.

We should decide if we want to support other OSs and if so, we have to change the test workflow to use a matrix strategy:

```
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [ubuntu-18.04, ubuntu-20.04]
    node: [10, 12, 14]
steps:
  - uses: actions/setup-node@v2
    with:
      node-version: ${{ matrix.node }}
```

GitHub docs:

- [Running with multiple operating systems](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-running-with-multiple-operating-systems#48)
- [Supported runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
